#!/bin/bash
#
# $Header: /home/garyb/FlashStick/CVSROOT/DigitalHome/Linux/usblta,v 1.1 2005/07/06 21:43:23 garyb Exp $
#
# (c) Copyright 2005, Gary Bartlett, Echelon Corporation.  All rights reserved.
#
# /etc/hotplug/usb/usblta
#
# Sets up newly plugged in USB LonTalk Adapter so that the user who owns
# the console according to pam_console can access it from user space.
#
# Note that for this script to work, you'll need all of the following:
# a) a line in the file /etc/hotplug/usermap that corresponds to the 
#    adapter you are using.
# b) a setup using pam_console creates the respective lock files
#    containing the name of the respective user.  You can check for that
#    by executing "echo `cat /var/{run,lock}/console.lock`" and 
#    verifying the appropriate user is mentioned somewhere there.
# c) a Linux kernel supporting hotplug and usbdevfs
# d) the hotplug package (http://linux-hotplug.sourceforge.net/)
#
# In the usermap file, the first field "usb module" should be named 
# "usblta" like this script.
# 

if [ "${ACTION}" = "add" ] && [ -f "${DEVICE}" ]
then
    # New code, using lock files instead of copying /dev/console permissions
    # This also works with non-gdm logins (e.g. on a virtual terminal)
    # Idea and code from Nalin Dahyabhai <nalin@redhat.com>
    if [ -f /var/run/console/console.lock ]
    then
        CONSOLEOWNER=`cat /var/run/console/console.lock`
    elif [ -f /var/run/console.lock ]
    then
        CONSOLEOWNER=`cat /var/run/console.lock`
    elif [ -f /var/lock/console.lock ]
    then
        CONSOLEOWNER=`cat /var/lock/console.lock`
    else
        CONSOLEOWNER=
    fi
    if [ -n "$CONSOLEOWNER" ]
    then
        chmod 0000 "${DEVICE}"
        chown "$CONSOLEOWNER" "${DEVICE}"
        chmod 0600 "${DEVICE}"
    else
        chmod 0666 "${DEVICE}"
    fi
fi
